{"name": "User enter incorrect data into the form", "status": "passed", "attachments": [{"name": "stdout", "source": "26702fad-707d-485b-ba57-cac5f91400c5-attachment.txt", "type": "text/plain"}], "start": 1647123462560, "stop": 1647123469037, "uuid": "8ec5f75e-5387-4fba-aa95-7f8c9fe16356", "historyId": "e660009e918cdac41d60d8a2e4568bd5", "testCaseId": "d99128bcf0f6f9e213eff44b4450554e", "fullName": "test_gui.TestsGUI#test_user_no_insert_data_to_form", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "suite", "value": "test_gui"}, {"name": "subSuite", "value": "TestsGUI"}, {"name": "host", "value": "LAPTOP-DKHHR5FU"}, {"name": "thread", "value": "10496-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_gui"}]}