{"name": "User enter incorrect data into the form", "status": "passed", "attachments": [{"name": "stdout", "source": "c2279b81-89d6-46b7-9989-f519a1fd1a41-attachment.txt", "type": "text/plain"}], "start": 1647122792803, "stop": 1647122799225, "uuid": "b5625a5c-702d-4c3f-be40-0126a0d390b1", "historyId": "e660009e918cdac41d60d8a2e4568bd5", "testCaseId": "d99128bcf0f6f9e213eff44b4450554e", "fullName": "test_gui.TestsGUI#test_user_no_insert_data_to_form", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "suite", "value": "test_gui"}, {"name": "subSuite", "value": "TestsGUI"}, {"name": "host", "value": "LAPTOP-DKHHR5FU"}, {"name": "thread", "value": "14528-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_gui"}]}