{"name": "User enter incorrect data into the form", "status": "passed", "attachments": [{"name": "stdout", "source": "92367949-a657-4005-b8fa-7ee75d3b3e7c-attachment.txt", "type": "text/plain"}], "start": 1647122134457, "stop": 1647122140514, "uuid": "56c4c921-6ef5-464e-ba40-0f8cd54424d4", "historyId": "e660009e918cdac41d60d8a2e4568bd5", "testCaseId": "d99128bcf0f6f9e213eff44b4450554e", "fullName": "test_gui.TestsGUI#test_user_no_insert_data_to_form", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "suite", "value": "test_gui"}, {"name": "subSuite", "value": "TestsGUI"}, {"name": "host", "value": "LAPTOP-DKHHR5FU"}, {"name": "thread", "value": "17168-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_gui"}]}